namespace WTF

type Bang() =
    let foo () =
        async {
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
            ignore 42
        }
